### ISSUE TITLE
Error with duration

### ISSUE THREAD

**Issue by SpinnerChris** [eas-alert/SAME-EAS-Encoder#2]
What are the NWR Specifications? I put the duration to 30 and I get this:
duration 30
usage: easencode.py [-h] [-v] [-z CUSTOM_MSG] [-x EOM] [-o ORIGINATOR]
                    [-e EVENT] [-f FIPS [FIPS2 ...]] [-d DURATION]
                    [-t TIMESTAMP] [-c CALLSIGN] [-a AUDIOIN]
                    OUTPUT.WAV
easencode.py: error: Invalid duration '30'

I tried looking up the NWR Specifications, but I found nothing.

**Comment by InsertNameHere42** [comment]
This isn't an issue, when it comes to NWR specifications, time is incremented in 15 minutes until 1 hour, then it is incremented in 30 minutes. the NWR Specifications look like this:

HHMM (Ex. for 15 minutes, would be 0015.) 

All null numbers are replaced with 0s, so for 15 minutes, (0 hours, 15 minutes) It would be 0015.

All NWR Specifications can be found at the following link:
[https://www.nws.noaa.gov/directives/sym/pd01017012curr.pdf](https://www.nws.noaa.gov/directives/sym/pd01017012curr.pdf)
I recommend to read this all the way through before using this program, provides a lot of insight.
