### ISSUE TITLE
Having issues running the code.

### ISSUE THREAD

**Issue by mcd573** [eas-alert/SAME-EAS-Encoder#3]
Hi, I found your program and am intersted in using it. However, your encoder program has a bunch of errors in it whenever I run it.

  File "K:\Downloads\RT.Util\SAME-EAS-Encoder\easencode.py", line 52
    if value is not None:
                        ^
TabError: inconsistent use of tabs and spaces in indentation

  File "K:\Downloads\RT.Util\SAME-EAS-Encoder\easencode.py", line 52
    if value is not None:
                        ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by InsertNameHere42** [comment]
Are you using Python2 with this program?

**Comment by mcd573** [comment]
I was able to resolve the issue by re-installing Python 2.7. Thanks for the assistance!
